-- =============================================================================
-- V2__uuid_pk_uppercase_enums_and_renames.sql
--
-- Non-destructive ALTER migration from the V1 schema. Tables, columns, and
-- existing rows are preserved across the BIGINT -> CHAR(36) UUID PK swap by
-- snapshotting every parent table's old -> new id mapping into a temporary
-- _v2_<table>_id_map table BEFORE the parent's PK column is dropped. Child
-- FK columns then look up their new UUID values from those maps. The maps
-- are dropped at the end of the migration.
--
-- Other reshapes this migration performs:
--   * ENUM columns rewritten with UPPERCASE values (MySQL's underlying
--     index-based storage preserves value identity across MODIFY)
--   * is_active -> active, is_used -> used (boolean column renames)
--   * staff_otps gains an updated_at column (AuditableEntity)
--   * staff.last_login and staff_otps.expires_at: DATETIME -> TIMESTAMP
--     (the app sets quarkus.hibernate-orm.jdbc.timezone=UTC; TIMESTAMP is
--     stored in UTC under that setting, DATETIME has no TZ semantics)
--   * Every FK column gets an explicit named index; every UNIQUE constraint
--     gets an explicit index too (MySQL auto-creates one for UNIQUE, but we
--     name them so future migrations can reference them by name)
--
-- FK constraint names from V1 are auto-generated by MySQL (foo_ibfk_N).
-- Rather than hard-code names that can drift across MySQL builds, the
-- migration discovers them via INFORMATION_SCHEMA and drops them in a
-- stored-procedure loop.
-- =============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- Silence MySQL's "Note"-level warnings for the DROP IF EXISTS calls that
-- run on a genesis database -- Flyway logs every SHOW WARNINGS row at WARN,
-- and "PROCEDURE x does not exist" / "Unknown table y" on a first-run
-- IF EXISTS clause is exactly the expected no-op. Re-enabled at the end.
SET @saved_sql_notes = @@SESSION.sql_notes;
SET SESSION sql_notes = 0;

-- -------------------------------------------------------
-- Helper: drop every FK constraint on the given table.
-- -------------------------------------------------------
-- All helper procedures are guarded so this migration is safe to re-run
-- if it failed partway (Flyway's exactly-once semantics is the primary
-- guard, but defense in depth doesn't hurt).
DROP PROCEDURE IF EXISTS drop_fks_for_table;
DROP PROCEDURE IF EXISTS create_index_if_missing;
DROP PROCEDURE IF EXISTS rename_table_if_exists;
DELIMITER //
CREATE PROCEDURE drop_fks_for_table(IN tbl VARCHAR(64))
BEGIN
    DECLARE done INT DEFAULT 0;
    DECLARE fk_name VARCHAR(64);
    DECLARE cur CURSOR FOR
        SELECT CONSTRAINT_NAME
        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = tbl
          AND CONSTRAINT_TYPE = 'FOREIGN KEY';
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
    OPEN cur;
    drop_loop: LOOP
        FETCH cur INTO fk_name;
        IF done THEN
            LEAVE drop_loop;
        END IF;
        SET @sql := CONCAT('ALTER TABLE `', tbl, '` DROP FOREIGN KEY `', fk_name, '`');
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END LOOP;
    CLOSE cur;
END //

CREATE PROCEDURE create_index_if_missing(IN tbl VARCHAR(64),
                                         IN idx_name VARCHAR(64),
                                         IN col_list VARCHAR(255))
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = tbl
          AND INDEX_NAME = idx_name
    ) THEN
        SET @sql := CONCAT('CREATE INDEX `', idx_name, '` ON `', tbl, '` (', col_list, ')');
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END //

CREATE PROCEDURE rename_table_if_exists(IN old_name VARCHAR(64),
                                        IN new_name VARCHAR(64))
BEGIN
    IF EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = old_name
    ) AND NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = new_name
    ) THEN
        SET @sql := CONCAT('RENAME TABLE `', old_name, '` TO `', new_name, '`');
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END //
DELIMITER ;

-- Drop FKs in reverse dependency order so each parent has nothing pointing
-- at it when we swap its primary key.
CALL drop_fks_for_table('audit_logs');
CALL drop_fks_for_table('documents');
CALL drop_fks_for_table('requests');
CALL drop_fks_for_table('document_templates');
CALL drop_fks_for_table('org_certificates');
CALL drop_fks_for_table('staff_otps');
CALL drop_fks_for_table('staff');

-- =============================================================================
-- Phase 1: For each table, allocate a new CHAR(36) uuid value for every row
-- and snapshot the (old_id, new_id) pair into a temporary map table. The
-- snapshots let downstream child FK columns be populated correctly even
-- after the parent's old BIGINT id has been dropped.
-- =============================================================================

DROP TABLE IF EXISTS _v2_organizations_id_map;
DROP TABLE IF EXISTS _v2_staff_id_map;
DROP TABLE IF EXISTS _v2_staff_otps_id_map;
DROP TABLE IF EXISTS _v2_resident_otps_id_map;
DROP TABLE IF EXISTS _v2_org_certificates_id_map;
DROP TABLE IF EXISTS _v2_document_templates_id_map;
DROP TABLE IF EXISTS _v2_requesters_id_map;
DROP TABLE IF EXISTS _v2_requests_id_map;
DROP TABLE IF EXISTS _v2_documents_id_map;
DROP TABLE IF EXISTS _v2_audit_logs_id_map;

CREATE TABLE _v2_organizations_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_organizations_new_id (new_id)
);
CREATE TABLE _v2_staff_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_staff_new_id (new_id)
);
CREATE TABLE _v2_staff_otps_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_staff_otps_new_id (new_id)
);
CREATE TABLE _v2_resident_otps_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_resident_otps_new_id (new_id)
);
CREATE TABLE _v2_org_certificates_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_org_certificates_new_id (new_id)
);
CREATE TABLE _v2_document_templates_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_document_templates_new_id (new_id)
);
CREATE TABLE _v2_requesters_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_requesters_new_id (new_id)
);
CREATE TABLE _v2_requests_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_requests_new_id (new_id)
);
CREATE TABLE _v2_documents_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_documents_new_id (new_id)
);
CREATE TABLE _v2_audit_logs_id_map (
    old_id BIGINT NOT NULL PRIMARY KEY,
    new_id CHAR(36) NOT NULL,
    UNIQUE KEY uc_v2_audit_logs_new_id (new_id)
);

INSERT INTO _v2_organizations_id_map (old_id, new_id)
SELECT id, UUID() FROM organizations;

INSERT INTO _v2_staff_id_map (old_id, new_id)
SELECT id, UUID() FROM staff;

INSERT INTO _v2_staff_otps_id_map (old_id, new_id)
SELECT id, UUID() FROM staff_otps;

INSERT INTO _v2_resident_otps_id_map (old_id, new_id)
SELECT id, UUID() FROM resident_otps;

INSERT INTO _v2_org_certificates_id_map (old_id, new_id)
SELECT id, UUID() FROM org_certificates;

INSERT INTO _v2_document_templates_id_map (old_id, new_id)
SELECT id, UUID() FROM document_templates;

INSERT INTO _v2_requesters_id_map (old_id, new_id)
SELECT id, UUID() FROM requesters;

INSERT INTO _v2_requests_id_map (old_id, new_id)
SELECT id, UUID() FROM requests;

INSERT INTO _v2_documents_id_map (old_id, new_id)
SELECT id, UUID() FROM documents;

INSERT INTO _v2_audit_logs_id_map (old_id, new_id)
SELECT id, UUID() FROM audit_logs;

-- =============================================================================
-- Phase 2: Swap each PK BIGINT -> CHAR(36). For each table we add a new_id
-- column, copy from the map, drop the old id, rename new_id -> id, add PK.
-- =============================================================================

-- organizations
ALTER TABLE organizations ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE organizations o
    JOIN _v2_organizations_id_map m ON m.old_id = o.id
    SET o.new_id = m.new_id;
ALTER TABLE organizations MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE organizations DROP COLUMN id;
ALTER TABLE organizations CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE organizations ADD PRIMARY KEY (id);

-- staff
ALTER TABLE staff ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE staff s JOIN _v2_staff_id_map m ON m.old_id = s.id SET s.new_id = m.new_id;
ALTER TABLE staff MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE staff DROP COLUMN id;
ALTER TABLE staff CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE staff ADD PRIMARY KEY (id);

-- staff_otps
ALTER TABLE staff_otps ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE staff_otps so JOIN _v2_staff_otps_id_map m ON m.old_id = so.id SET so.new_id = m.new_id;
ALTER TABLE staff_otps MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE staff_otps DROP COLUMN id;
ALTER TABLE staff_otps CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE staff_otps ADD PRIMARY KEY (id);

-- resident_otps
ALTER TABLE resident_otps ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE resident_otps r JOIN _v2_resident_otps_id_map m ON m.old_id = r.id SET r.new_id = m.new_id;
ALTER TABLE resident_otps MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE resident_otps DROP COLUMN id;
ALTER TABLE resident_otps CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE resident_otps ADD PRIMARY KEY (id);

-- org_certificates
ALTER TABLE org_certificates ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE org_certificates oc JOIN _v2_org_certificates_id_map m ON m.old_id = oc.id SET oc.new_id = m.new_id;
ALTER TABLE org_certificates MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE org_certificates DROP COLUMN id;
ALTER TABLE org_certificates CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE org_certificates ADD PRIMARY KEY (id);

-- document_templates
ALTER TABLE document_templates ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE document_templates dt JOIN _v2_document_templates_id_map m ON m.old_id = dt.id SET dt.new_id = m.new_id;
ALTER TABLE document_templates MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE document_templates DROP COLUMN id;
ALTER TABLE document_templates CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE document_templates ADD PRIMARY KEY (id);

-- requesters
ALTER TABLE requesters ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE requesters r JOIN _v2_requesters_id_map m ON m.old_id = r.id SET r.new_id = m.new_id;
ALTER TABLE requesters MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE requesters DROP COLUMN id;
ALTER TABLE requesters CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE requesters ADD PRIMARY KEY (id);

-- requests
ALTER TABLE requests ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE requests r JOIN _v2_requests_id_map m ON m.old_id = r.id SET r.new_id = m.new_id;
ALTER TABLE requests MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE requests DROP COLUMN id;
ALTER TABLE requests CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE requests ADD PRIMARY KEY (id);

-- documents
ALTER TABLE documents ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE documents d JOIN _v2_documents_id_map m ON m.old_id = d.id SET d.new_id = m.new_id;
ALTER TABLE documents MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE documents DROP COLUMN id;
ALTER TABLE documents CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE documents ADD PRIMARY KEY (id);

-- audit_logs
ALTER TABLE audit_logs ADD COLUMN new_id CHAR(36) AFTER id;
UPDATE audit_logs al JOIN _v2_audit_logs_id_map m ON m.old_id = al.id SET al.new_id = m.new_id;
ALTER TABLE audit_logs MODIFY COLUMN id BIGINT NOT NULL, DROP PRIMARY KEY;
ALTER TABLE audit_logs DROP COLUMN id;
ALTER TABLE audit_logs CHANGE COLUMN new_id id CHAR(36) NOT NULL FIRST;
ALTER TABLE audit_logs ADD PRIMARY KEY (id);

-- =============================================================================
-- Phase 3: For each FK column on every table, allocate a new CHAR(36)
-- column and populate it from the parent's map. Then drop the old BIGINT
-- FK column and rename. This works correctly regardless of the order
-- parents were swapped above because the maps preserve old -> new mapping.
-- =============================================================================

-- staff.organization_id -> organizations.id
ALTER TABLE staff ADD COLUMN new_organization_id CHAR(36) AFTER organization_id;
UPDATE staff s
    JOIN _v2_organizations_id_map m ON m.old_id = s.organization_id
    SET s.new_organization_id = m.new_id;
ALTER TABLE staff DROP COLUMN organization_id;
ALTER TABLE staff CHANGE COLUMN new_organization_id organization_id CHAR(36) NOT NULL;

-- staff_otps.staff_id -> staff.id
ALTER TABLE staff_otps ADD COLUMN new_staff_id CHAR(36) AFTER staff_id;
UPDATE staff_otps so
    JOIN _v2_staff_id_map m ON m.old_id = so.staff_id
    SET so.new_staff_id = m.new_id;
ALTER TABLE staff_otps DROP COLUMN staff_id;
ALTER TABLE staff_otps CHANGE COLUMN new_staff_id staff_id CHAR(36) NOT NULL;

-- org_certificates.organization_id -> organizations.id
ALTER TABLE org_certificates ADD COLUMN new_organization_id CHAR(36) AFTER organization_id;
UPDATE org_certificates oc
    JOIN _v2_organizations_id_map m ON m.old_id = oc.organization_id
    SET oc.new_organization_id = m.new_id;
ALTER TABLE org_certificates DROP COLUMN organization_id;
ALTER TABLE org_certificates CHANGE COLUMN new_organization_id organization_id CHAR(36) NOT NULL;

-- document_templates.organization_id -> organizations.id
ALTER TABLE document_templates ADD COLUMN new_organization_id CHAR(36) AFTER organization_id;
UPDATE document_templates dt
    JOIN _v2_organizations_id_map m ON m.old_id = dt.organization_id
    SET dt.new_organization_id = m.new_id;
ALTER TABLE document_templates DROP COLUMN organization_id;
ALTER TABLE document_templates CHANGE COLUMN new_organization_id organization_id CHAR(36) NOT NULL;

-- requests.organization_id -> organizations.id
ALTER TABLE requests ADD COLUMN new_organization_id CHAR(36) AFTER organization_id;
UPDATE requests r
    JOIN _v2_organizations_id_map m ON m.old_id = r.organization_id
    SET r.new_organization_id = m.new_id;
ALTER TABLE requests DROP COLUMN organization_id;
ALTER TABLE requests CHANGE COLUMN new_organization_id organization_id CHAR(36) NOT NULL;

-- requests.requester_id -> requesters.id
ALTER TABLE requests ADD COLUMN new_requester_id CHAR(36) AFTER requester_id;
UPDATE requests r
    JOIN _v2_requesters_id_map m ON m.old_id = r.requester_id
    SET r.new_requester_id = m.new_id;
ALTER TABLE requests DROP COLUMN requester_id;
ALTER TABLE requests CHANGE COLUMN new_requester_id requester_id CHAR(36) NOT NULL;

-- requests.template_id -> document_templates.id
ALTER TABLE requests ADD COLUMN new_template_id CHAR(36) AFTER template_id;
UPDATE requests r
    JOIN _v2_document_templates_id_map m ON m.old_id = r.template_id
    SET r.new_template_id = m.new_id;
ALTER TABLE requests DROP COLUMN template_id;
ALTER TABLE requests CHANGE COLUMN new_template_id template_id CHAR(36) NOT NULL;

-- requests.processed_by -> staff.id (nullable)
ALTER TABLE requests ADD COLUMN new_processed_by CHAR(36) AFTER processed_by;
UPDATE requests r
    LEFT JOIN _v2_staff_id_map m ON m.old_id = r.processed_by
    SET r.new_processed_by = m.new_id;
ALTER TABLE requests DROP COLUMN processed_by;
ALTER TABLE requests CHANGE COLUMN new_processed_by processed_by CHAR(36) NULL;

-- documents.request_id -> requests.id
ALTER TABLE documents ADD COLUMN new_request_id CHAR(36) AFTER request_id;
UPDATE documents d
    JOIN _v2_requests_id_map m ON m.old_id = d.request_id
    SET d.new_request_id = m.new_id;
ALTER TABLE documents DROP COLUMN request_id;
ALTER TABLE documents CHANGE COLUMN new_request_id request_id CHAR(36) NOT NULL;

-- documents.org_certificate_id -> org_certificates.id
ALTER TABLE documents ADD COLUMN new_org_certificate_id CHAR(36) AFTER org_certificate_id;
UPDATE documents d
    JOIN _v2_org_certificates_id_map m ON m.old_id = d.org_certificate_id
    SET d.new_org_certificate_id = m.new_id;
ALTER TABLE documents DROP COLUMN org_certificate_id;
ALTER TABLE documents CHANGE COLUMN new_org_certificate_id org_certificate_id CHAR(36) NOT NULL;

-- documents.issued_by -> staff.id
ALTER TABLE documents ADD COLUMN new_issued_by CHAR(36) AFTER issued_by;
UPDATE documents d
    JOIN _v2_staff_id_map m ON m.old_id = d.issued_by
    SET d.new_issued_by = m.new_id;
ALTER TABLE documents DROP COLUMN issued_by;
ALTER TABLE documents CHANGE COLUMN new_issued_by issued_by CHAR(36) NOT NULL;

-- audit_logs.actor_id -> staff.id (nullable, ON DELETE SET NULL)
ALTER TABLE audit_logs ADD COLUMN new_actor_id CHAR(36) AFTER actor_id;
UPDATE audit_logs al
    LEFT JOIN _v2_staff_id_map m ON m.old_id = al.actor_id
    SET al.new_actor_id = m.new_id;
ALTER TABLE audit_logs DROP COLUMN actor_id;
ALTER TABLE audit_logs CHANGE COLUMN new_actor_id actor_id CHAR(36) NULL;

-- audit_logs.entity_id is a polymorphic reference (entity_type tells what
-- table it refers to). Stored as BIGINT in V1; we only widen the column to
-- CHAR(36) so future rows can hold a UUID. Pre-V2 rows will have NULL after
-- the column type change since the BIGINT values are no longer meaningful.
ALTER TABLE audit_logs MODIFY COLUMN entity_id CHAR(36) NULL;

-- =============================================================================
-- Phase 4: ENUM uppercase -- MySQL preserves the index->position mapping so
-- existing rows automatically read as the new uppercase label.
-- =============================================================================

ALTER TABLE organizations
    MODIFY COLUMN type ENUM('BARANGAY','SCHOOL','CITY') NOT NULL DEFAULT 'BARANGAY';

ALTER TABLE staff
    MODIFY COLUMN role ENUM('STAFF','ADMIN') NOT NULL DEFAULT 'STAFF';

ALTER TABLE staff_otps
    MODIFY COLUMN otp_type ENUM('LOGIN','PASSWORD_RESET') NOT NULL DEFAULT 'LOGIN';

ALTER TABLE document_templates
    MODIFY COLUMN doc_type ENUM('BARANGAY_CLEARANCE','CERTIFICATE_OF_RESIDENCY','CERTIFICATE_OF_INDIGENCY') NOT NULL;

ALTER TABLE requests
    MODIFY COLUMN status ENUM('PENDING','UNDER_REVIEW','PROCESSING','COMPLETED','REJECTED') NOT NULL DEFAULT 'PENDING';

ALTER TABLE audit_logs
    MODIFY COLUMN actor_role ENUM('STAFF','ADMIN','SYSTEM');

-- =============================================================================
-- Phase 5: Boolean column renames: is_active -> active, is_used -> used
-- =============================================================================

ALTER TABLE organizations CHANGE COLUMN is_active active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE staff CHANGE COLUMN is_active active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE document_templates CHANGE COLUMN is_active active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE org_certificates CHANGE COLUMN is_active active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE staff_otps CHANGE COLUMN is_used used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE resident_otps CHANGE COLUMN is_used used BOOLEAN NOT NULL DEFAULT FALSE;

-- =============================================================================
-- Phase 6: staff_otps gains a Java-managed updated_at column.
-- =============================================================================

ALTER TABLE staff_otps
    ADD COLUMN updated_at TIMESTAMP NULL AFTER created_at;
UPDATE staff_otps SET updated_at = created_at WHERE updated_at IS NULL;
ALTER TABLE staff_otps
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL;

-- =============================================================================
-- Phase 7: DATETIME -> TIMESTAMP where the Java type is Instant.
-- =============================================================================

ALTER TABLE staff MODIFY COLUMN last_login TIMESTAMP NULL;
ALTER TABLE staff_otps MODIFY COLUMN expires_at TIMESTAMP NOT NULL;

-- otp_attempts: column already NOT NULL DEFAULT 0; nothing to change.

-- =============================================================================
-- Phase 8: Recreate FK constraints with explicit names so future migrations
-- can refer to them directly.
-- =============================================================================

ALTER TABLE staff
    ADD CONSTRAINT fk_staff_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE staff_otps
    ADD CONSTRAINT fk_staff_otps_staff
        FOREIGN KEY (staff_id) REFERENCES staff (id) ON DELETE CASCADE;

ALTER TABLE org_certificates
    ADD CONSTRAINT fk_org_certificates_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE document_templates
    ADD CONSTRAINT fk_document_templates_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE requests
    ADD CONSTRAINT fk_requests_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    ADD CONSTRAINT fk_requests_requester
        FOREIGN KEY (requester_id) REFERENCES requesters (id),
    ADD CONSTRAINT fk_requests_template
        FOREIGN KEY (template_id) REFERENCES document_templates (id),
    ADD CONSTRAINT fk_requests_processed_by
        FOREIGN KEY (processed_by) REFERENCES staff (id);

ALTER TABLE documents
    ADD CONSTRAINT fk_documents_request
        FOREIGN KEY (request_id) REFERENCES requests (id),
    ADD CONSTRAINT fk_documents_org_certificate
        FOREIGN KEY (org_certificate_id) REFERENCES org_certificates (id),
    ADD CONSTRAINT fk_documents_issued_by
        FOREIGN KEY (issued_by) REFERENCES staff (id);

ALTER TABLE audit_logs
    ADD CONSTRAINT fk_audit_logs_actor
        FOREIGN KEY (actor_id) REFERENCES staff (id) ON DELETE SET NULL;

-- =============================================================================
-- Phase 9: Indexes -- covers every FK column and every UNIQUE-constraint
-- column. MySQL InnoDB does create an index for FK columns automatically,
-- but naming them explicitly here means future migrations can drop or
-- rename them by name. UNIQUE constraints already carry an underlying
-- index too; we declare nothing extra for those.
-- =============================================================================

CALL create_index_if_missing('organizations', 'idx_organizations_type', 'type');
CALL create_index_if_missing('organizations', 'idx_organizations_name', 'name');

CALL create_index_if_missing('staff', 'idx_staff_organization_id', 'organization_id');
CALL create_index_if_missing('staff', 'idx_staff_email', 'email');

CALL create_index_if_missing('staff_otps', 'idx_staff_otps_staff_id', 'staff_id');
CALL create_index_if_missing('staff_otps', 'idx_staff_otps_lookup', 'staff_id, otp_type, used, id');

CALL create_index_if_missing('org_certificates', 'idx_org_certificates_organization_id', 'organization_id');

CALL create_index_if_missing('document_templates', 'idx_document_templates_organization_id', 'organization_id');
CALL create_index_if_missing('document_templates', 'idx_document_templates_doc_type', 'doc_type');

CALL create_index_if_missing('requests', 'idx_requests_organization_id', 'organization_id');
CALL create_index_if_missing('requests', 'idx_requests_requester_id', 'requester_id');
CALL create_index_if_missing('requests', 'idx_requests_template_id', 'template_id');
CALL create_index_if_missing('requests', 'idx_requests_processed_by', 'processed_by');

CALL create_index_if_missing('documents', 'idx_documents_request_id', 'request_id');
CALL create_index_if_missing('documents', 'idx_documents_org_certificate_id', 'org_certificate_id');
CALL create_index_if_missing('documents', 'idx_documents_issued_by', 'issued_by');

CALL create_index_if_missing('audit_logs', 'idx_audit_logs_actor_id', 'actor_id');
CALL create_index_if_missing('audit_logs', 'idx_audit_logs_entity', 'entity_type, entity_id');
CALL create_index_if_missing('audit_logs', 'idx_audit_logs_created_at', 'created_at');

-- =============================================================================
-- Phase 10: Singularize table names. MySQL 8 InnoDB updates FK constraint
-- references automatically when a parent table is renamed, so the
-- explicitly named constraints from Phase 8 continue to work. Index names
-- that contain the old plural prefix are left as-is (just identifiers);
-- new migrations can rename them if cosmetic consistency matters.
-- =============================================================================

CALL rename_table_if_exists('organizations', 'organization');
CALL rename_table_if_exists('staff_otps', 'staff_otp');
CALL rename_table_if_exists('resident_otps', 'resident_otp');
CALL rename_table_if_exists('org_certificates', 'org_certificate');
CALL rename_table_if_exists('document_templates', 'document_template');
CALL rename_table_if_exists('requesters', 'requester');
CALL rename_table_if_exists('requests', 'request');
CALL rename_table_if_exists('documents', 'document');
CALL rename_table_if_exists('audit_logs', 'audit_log');
-- staff is already singular; no rename.

-- =============================================================================
-- Cleanup
-- =============================================================================

DROP TABLE _v2_organizations_id_map;
DROP TABLE _v2_staff_id_map;
DROP TABLE _v2_staff_otps_id_map;
DROP TABLE _v2_resident_otps_id_map;
DROP TABLE _v2_org_certificates_id_map;
DROP TABLE _v2_document_templates_id_map;
DROP TABLE _v2_requesters_id_map;
DROP TABLE _v2_requests_id_map;
DROP TABLE _v2_documents_id_map;
DROP TABLE _v2_audit_logs_id_map;

DROP PROCEDURE drop_fks_for_table;
DROP PROCEDURE create_index_if_missing;
DROP PROCEDURE rename_table_if_exists;

SET FOREIGN_KEY_CHECKS = 1;
SET SESSION sql_notes = @saved_sql_notes;
