package com.oppshan.securedoc.common;

import java.time.Instant;
import java.util.UUID;

/**
 * Contract every persistent entity satisfies. The primary key is a
 * UUID (v7, time-ordered) generated by Hibernate's
 * {@code @UuidGenerator(style = VERSION_7)}; the listener
 * {@link AuditableEntityEntityListener} sets the temporal fields on
 * {@code @PrePersist} / {@code @PreUpdate}.
 */
public interface AuditableEntity<T extends AuditableEntity<T>> {

    UUID getId();

    T setId(UUID id);

    Instant getCreatedAt();

    T setCreatedAt(Instant createdAt);

    Instant getLastModifiedAt();

    T setLastModifiedAt(Instant lastModifiedAt);
}
